#ifndef _PF_PHASE_ENUM_
#define _PF_PHASE_ENUM_

#define INACTIVE -99
#define INACTIVE_DATA_LOADED -98
#define RUNNING_A_AR_TEST -60
#define RUNNING_A_BR_TEST -40
#define SYNC_TRACKER_START_ONLY -26
#define SYNC_TRACKER_LATERAL_DISABLED -25
#define SYNC_TRACKER_LONGITUDINAL_DISABLED -24
#define RUNNING_A_SR_TEST -20
#define AT_STOP_POINT -18
#define BR_DOING_NORMAL_STOP -17
#define BR_DOING_ABORT_STOP -16
#define BR_ABORT_FROM_CS -15
#define ON_EXIT_LAP -14
#define IN_VIRTUAL_GUIDE_RAIL -9
#define IN_CRITICAL_SECTION -8
#define SYNC_TRACKER_DISABLED -6
#define SYNC_TRACKER_FULLY_ENABLED -5
#define ON_ENTRY_LAP -4
#define TRANSITION_BETWEEN_PATHS -1
#define ON_LEAD_IN 0 


// Positive values are lap counters

#endif
