#ifndef _TEST_STATE_ENUM_
#define _TEST_STATE_ENUM_

#define GOING_DRIVERLESS -1
#define NOT_ACTIVE 0
#define WAIT_FOR_READY 1
#define WAIT_FOR_START 2
#define MANUAL_MODE_PRETEST 3
#define TEST_RUNNING 4
#define SR_TEST_COMPLETE 5
#define SR_BR_TEST_COMPLETE 6
#define MANUAL_MODE_POSTTEST 7
#define RAPID_STOPPING 8
#define E_STOPPING 9
#define NO_CONTROL_POSSIBLE 10
#define TEST_FINISH 11
#define PC_SIGNAL_STOP 12

#endif
